# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20160706_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project_img')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
