# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_auto_20160707_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Front End'), (1, 'Back End'), (2, 'iOS'), (3, 'Android'), (4, 'Other')], default=0),
        ),
    ]
