# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_auto_20160830_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Web'), (1, 'iOS'), (2, 'Android'), (3, 'Desktop')], default=0),
        ),
    ]
